AppUni.WEB.MVC/Models/ErrorViewModel.cs
namespace AppUni.WEB.MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AppUni.WEB.MVC/Controllers/CarrerasController.cs
using AppUni.ConsumeAPI;
using AppUni.Entidades;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace AppUni.WEB.MVC.Controllers
{
    public class CarrerasController : Controller
    {
        private readonly string urlApi;
        private string urlBase;

        public CarrerasController(IConfiguration configuration)
        {
            urlApi = configuration.GetValue("ApiUrlBase", "").ToString() + "/Carreras";
            this.urlBase = configuration.GetValue("ApiUrlBase", "").ToString();

        }
        private Universidad[] ObtenerListaDepartamentos()
        {

            return Crud<Universidad>.Read(urlBase + "/Universidades");
        }
        // GET: CarrerasController
        public ActionResult Index()
        {
            var data = Crud<Carrera>.Read(urlApi);
            return View(data);
        }

        // GET: CarrerasController/Details/5
        public ActionResult Details(int id)
        {
            var data = Crud<Carrera>.Read_ById(urlApi, id);
            return View(data);
        }

        // GET: CarrerasController/Create
        public ActionResult Create()
        {
            ViewBag.UniversidadId = ObtenerListaDepartamentos().Select(d => new SelectListItem
            {
                Value = d.Id.ToString(),
                Text = d.Nombre
            }).ToList();
            return View();
        }

        // POST: CarrerasController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Carrera data)
        {
            try
            {
                var newData = Crud<Carrera>.Create(urlApi, data);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        // GET: CarrerasController/Edit/5
        public ActionResult Edit(int id)
        {
            var data = Crud<Carrera>.Read_ById(urlApi, id);
            return View(data);
        }

        // POST: CarrerasController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Carrera data)
        {
            try
            {
                Crud<Carrera>.Update(urlApi, id, data);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        // GET: CarrerasController/Delete/5
        public ActionResult Delete(int id)
        {
            var data = Crud<Carrera>.Read_ById(urlApi, id);
            return View(data);
        }

        // POST: CarrerasController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Carrera data)
        {
            try
            {
                Crud<Carrera>.Delete(urlApi, id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }
    }
}

AppUni.WEB.MVC/Controllers/HomeController.cs
using AppUni.WEB.MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AppUni.WEB.MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AppUni.WEB.MVC/Controllers/UniversidadesController.cs
using AppUni.ConsumeAPI;
using AppUni.Entidades;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AppUni.WEB.MVC.Controllers
{
    public class UniversidadesController : Controller
    {
        private readonly string urlApi;
        public UniversidadesController(IConfiguration configuration)
        {
            urlApi = configuration.GetValue("ApiUrlBase", "").ToString() + "/Universidades";
        }
        // GET: UniversidadesController
        public ActionResult Index()
        {
            var data = Crud<Universidad>.Read(urlApi);
            return View(data);
        }

        // GET: UniversidadesController/Details/5
        public ActionResult Details(int id)
        {
            var data = Crud<Universidad>.Read_ById(urlApi, id);
            return View(data);
        }

        // GET: UniversidadesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UniversidadesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Universidad data)
        {
            try
            {
                var newData = Crud<Universidad>.Create(urlApi, data);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        // GET: UniversidadesController/Edit/5
        public ActionResult Edit(int id)
        {
            var data = Crud<Universidad>.Read_ById(urlApi, id);
            return View(data);
        }

        // POST: UniversidadesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Universidad data)
        {
            try
            {
                Crud<Universidad>.Update(urlApi, id, data);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }

        // GET: UniversidadesController/Delete/5
        public ActionResult Delete(int id)
        {
            var data = Crud<Universidad>.Read_ById(urlApi, id);
            return View(data);
        }

        // POST: UniversidadesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Universidad data)
        {
            try
            {
                Crud<Universidad>.Delete(urlApi, id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View();
            }
        }
    }
}

AppUni.WEB.MVC/Views/Carreras/Create.cshtml
@model AppUni.Entidades.Carrera

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Carrera</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           @*  <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UniversidadId" class="control-label"></label>
                <select asp-for="UniversidadId" class="form-control" asp-items="ViewBag.UniversidadId"></select>
                <span asp-validation-for="UniversidadId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppUni.WEB.MVC/Views/Carreras/Delete.cshtml
@model AppUni.Entidades.Carrera

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Carrera</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UniversidadId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UniversidadId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AppUni.WEB.MVC/Views/Carreras/Details.cshtml
@model AppUni.Entidades.Carrera

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Carrera</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UniversidadId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UniversidadId)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

AppUni.WEB.MVC/Views/Carreras/Edit.cshtml
@model AppUni.Entidades.Carrera

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Carrera</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" disabled />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UniversidadId" class="control-label"></label>
                <input asp-for="UniversidadId" class="form-control" />
                <span asp-validation-for="UniversidadId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppUni.WEB.MVC/Views/Carreras/Index.cshtml
@model IEnumerable<AppUni.Entidades.Carrera>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UniversidadId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Universidad.Nombre)
            </td>
            <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

AppUni.WEB.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container text-center">
    <h1 class="display-4">EXAMEN ANGELO VACA</h1>
    <p class="lead">Universidad-Carreras</p>
    <p class="text-muted">La aplicación desarrollada en Visual Studio consiste en tres proyectos: uno para la API (AppUni.API), otro para las entidades (AppUni.Entidades), y un tercero para la interfaz web MVC (AppUni.WEB.MVC). En el proyecto de entidades, se definen las clases Universidad y Carrera, donde una universidad puede tener múltiples carreras, representando una relación uno a muchos. En el proyecto API, se configura un DbContext para manejar estas entidades y se establece la conexión a una base de datos SQL Server, además de crear controladores API para realizar operaciones CRUD (Crear, Leer, Actualizar y Eliminar) sobre las entidades. En el proyecto web MVC, se crea la interfaz de usuario utilizando Razor Views y controladores MVC para interactuar con la API, permitiendo a los usuarios gestionar universidades y carreras a través de una interfaz web intuitiva y amigable. Esto integra backend y frontend, facilitando la administración de datos y la visualización de la información en tiempo real.</p>
    <img class="img-fluid" src="https://images.pexels.com/photos/2982449/pexels-photo-2982449.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1" alt="Imagen representativa">
</div>

AppUni.WEB.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppUni.WEB.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AppUni.WEB.MVC.styles.css" asp-append-version="true" />
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppUni.WEB.MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Universidades" asp-action="Index">Universidades</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Carreras" asp-action="Index">Carreras</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AppUni.WEB.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AppUni.WEB.MVC/Views/Universidades/Create.cshtml
@model AppUni.Entidades.Universidad

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Universidad</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @* <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ubicacion" class="control-label"></label>
                <input asp-for="Ubicacion" class="form-control" />
                <span asp-validation-for="Ubicacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppUni.WEB.MVC/Views/Universidades/Delete.cshtml
@model AppUni.Entidades.Universidad

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Universidad</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ubicacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ubicacion)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

AppUni.WEB.MVC/Views/Universidades/Details.cshtml
@model AppUni.Entidades.Universidad

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Universidad</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ubicacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ubicacion)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

AppUni.WEB.MVC/Views/Universidades/Edit.cshtml
@model AppUni.Entidades.Universidad

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Universidad</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" disabled />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ubicacion" class="control-label"></label>
                <input asp-for="Ubicacion" class="form-control" />
                <span asp-validation-for="Ubicacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AppUni.WEB.MVC/Views/Universidades/Index.cshtml
@model IEnumerable<AppUni.Entidades.Universidad>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ubicacion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ubicacion)
            </td>
            <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
}
    </tbody>
</table>